
const { PORT, MONGODB_URI, JWT_ACCESS_TOKEN, JWT_REFRESH_TOKEN  ,
    REACT_APP_URL, GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET
} = process.env;

module.exports = {
    PORT,
    MONGODB_URI,
    JWT_ACCESS_TOKEN,
    JWT_REFRESH_TOKEN,
    REACT_APP_URL,
    GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET,
};